POST http://localhost:3001/api/patients 

Content-Type: application/json
{
    "name": "Hans Gasdruber",
    "dateOfBirth": "1970asd-04-25",
    "ssn": "250470-555L",
    "gender": "male",
    "occupation": "Technician",
}