POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "hudde",
    "name": "hudde1234",
    "password": "hudde"
    
}
###
POST http://localhost:3003/api/blogs

###
DELETE  http://localhost:3003/api/blogs/61fd119f39a82e056924e714
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imh1ZGRlIiwiaWQiOiI2MWZkMTIxNDM5YTgyZTA1NjkyNGU3MWUiLCJpYXQiOjE2NDM5NzUyMDQsImV4cCI6MTY0Mzk3ODgwNH0.h3SodLaO15JrTMqndst5CcpYZQ1Cvl7QlLcWz7W3Ews
###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imh1cnJlZWVlIiwiaWQiOiI2MWYzYzcyM2M4ZjNlZTY3ODQ3YzkwNDEiLCJpYXQiOjE2NDMzODQ3NTd9.kDPLHRYrJjNMtAL4YCtNq5p30tnoP-hxT9KidJyNqu0

{
    "title": "asd34",
    "author": "uusdddasd34d123",
    "url": "uus.coddasdd34m",
    "likes": 3226
}