POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "username": "joku",
    "name": "pepe",
    "password": "moi"
    
}
###

DELETE  http://localhost:3003/api/blogs/61e9550225017600a8a37762

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "uuss",
    "author": "jekkksp",
    "url": "httkkkksp abc",
    "likes": 306,
    "userId": "61f17be641aac516fad1a98d"
}