POST http://localhost:3003/api/users
{
    "username": "hurre",
    "name": "hudde123",
    "password": "hello"
    
}
###

DELETE  http://localhost:3003/api/blogs/61e9550225017600a8a37762

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "uudempi",
    "author": "uus123",
    "url": "uus.com",
    "likes": 326,
    "userId": "61f17be641aac516fad1a98d"
}